name: build

on:
  push:
  pull_request:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phases:
    uses: cargo-checkmate/cargo-checkmate/.github/workflows/callee.yaml@gh-callee-v1

  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: cargo-onedoc

    - name: Check README
      run: cargo onedoc --check
